branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - node
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
